name = "stats"
compatibility_date = "2025-07-18"
pages_build_output_dir = "."  # Current directory since we're serving static files

[build]
command = "npm run build"

# For Cloudflare Pages Functions
[functions]
directory = "."  # Look for _worker.js in the root

# For static assets
[site]
bucket = "."  # Serve all files in the current directory
